# COMBINE GVCFs generated by SAREK (HaplotypeCaller). This consists of merging each sample vcf into one unique file per family. Afterwards, onve the gVCFs are merged, the joint call is carried out

#conda activate nf-core-sarek-2.6-fix-gatk for all steps.

find ../02-sarek/VariantCalling/ -name "HaplotypeCaller*.g.vcf.gz" > samples.list
mkdir 00-combine_gvcfs
mkdir 01-joint_call
qsub -V -b y -j y -cwd -N COMBINEGVCFs -q numerobis.q gatk CombineGVCFs \
	-R <path/to/WholeGenomeFasta/Homo_sapiens_assembly38.fasta> \
    -V samples.list \
    -O ./00-combine_gvcfs/family.g.vcf.gz 


#JOINT GENOTYPING on a cohort by providing a combined multi-sample GCVF from each family.

qsub -V -b y -j y -cwd -N JOINTCALL -q all.q gatk --java-options "-Xmx4g" GenotypeGVCFs \
      -R <path/to/WholeGenomeFasta/Homo_sapiens_assembly38.fasta> \
      -V ./00-combine_gvcfs/family.g.vcf.gz \
      -O ./01-joint_call/family.vcf.gz

# VARIANT FILTRATION based on quality scores

qsub -V -b y -j y -cwd -N SELSNPS -q all.q gatk SelectVariants \
     -V ./01-joint_call/family.vcf.gz \
     -select-type SNP \
     -O snps.vcf.gz

qsub -V -b y -j y -cwd -N SELINDELS -q all.q gatk SelectVariants \
    -V ./01-joint_call/family.vcf.gz \
    -select-type INDEL \
    -O indels.vcf.gz

gatk --java-options "-Xmx4g" VariantFiltration \
	-V snps.vcf.gz \
	-filter "QD < 2.0" --filter-name "QD2" \
	-filter "QUAL < 30.0" --filter-name "QUAL30" \
	-filter "SOR > 3.0" --filter-name "SOR3" \
	-filter "FS > 60.0" --filter-name "FS60" \
	-filter "MQ < 40.0" --filter-name "MQ40" \
	-filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5" \
	-filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8" \
	-O snps_filtered.vcf.gz

gatk --java-options "-Xmx4g" VariantFiltration \
	-V indels.vcf.gz \
	-filter "QD < 2.0" --filter-name "QD2" \
	-filter "QUAL < 30.0" --filter-name "QUAL30" \
	-filter "FS > 200.0" --filter-name "FS200" \
	-filter "ReadPosRankSum < -20.0" --filter-name "ReadPosRankSum-20" \
	-O indels_filtered.vcf.gz

qsub -V -b y -j y -cwd -N MERGEVCFS -q all.q gatk MergeVcfs \
	-I ./snps_filtered.vcf.gz \
	-I ./indels_filtered.vcf.gz \
	-O variants_fil.vcf.gz

bgzip -d variants_fil.vcf.gz

# SPLITTING into individual samples
cat ../../samples_id.txt | xargs -I % echo "bcftools view -c1 -Oz -s % -o %_new.vcf.gz variants_fil.vcf" > _08_split_samples.sh

cat ../../samples_id.txt | xargs -I % echo "gzip -d %_new.vcf.gz"  > _09_decompress.sh
